spring.datasource.url=jdbc:postgresql://localhost:5432/novabank
spring.datasource.username=postgres
spring.datasource.password=655057621
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci√≥n de JPA/Hibernate
# 'update' actualiza la tabla autom√°ticamente si a√±ades columnas a tus entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACI”N DE SEGURIDAD (JWT / ADMIN)
# ==========================================
api.security.admin.username=admin
# Le decimos a Spring que busque la variable en el entorno de tu PC.
# Si no la encuentra, usar· "clave_falsa" por defecto.
api.security.admin.password=${API_ADMIN_PASSWORD:clave_falsa}
